import React from 'react';

const dataType = {
	[process.env.DATA_TYPE_INT]: {
		id: process.env.DATA_TYPE_INT,
		name: () => 'Целое число',
		label: () => 'Целое число',
		placeholder: () => 0,
		defaultValue: () => '',
		component: () => React.lazy(() => import('components/Input/Int')),
	},
	[process.env.DATA_TYPE_FLOAT]: {
		id: process.env.DATA_TYPE_FLOAT,
		name: () => 'Дробное число',
		label: () => 'Дробное число',
		placeholder: () => 0,
		defaultValue: () => '',
		component: () => React.lazy(() => import('components/Input/Float')),
	},
	[process.env.DATA_TYPE_BOOLEAN]: {
		id: process.env.DATA_TYPE_BOOLEAN,
		name: () => 'Логический тип (boolean)',
		label: () => 'Логический тип (boolean)',
		placeholder: () => '',
		defaultValue: () => false,
		component: () => React.lazy(() => import('components/Input/Bool')),
	},
	[process.env.DATA_TYPE_TEXT]: {
		id: process.env.DATA_TYPE_TEXT,
		name: () => 'Строка',
		label: () => 'Строка',
		placeholder: () => 'text...',
		defaultValue: () => '',
		component: () => React.lazy(() => import('components/Input/Text')),
	},
	[process.env.DATA_TYPE_RICHTEXT]: {
		id: process.env.DATA_TYPE_RICHTEXT,
		name: () => 'Текстовый редактор',
		label: () => 'Текстовый редактор',
		placeholder: () => 'text...',
		defaultValue: () => '',
		component: () => React.lazy(() => import('components/Input/Richtext')),
	},
	[process.env.DATA_TYPE_PHONE]: {
		id: process.env.DATA_TYPE_PHONE,
		name: () => 'Номер телефона',
		label: () => 'Номер телефона',
		placeholder: () => '+79...',
		defaultValue: () => '',
		component: () => React.lazy(() => import('components/Input/Phone')),
	},
	[process.env.DATA_TYPE_EMAIL]: {
		id: process.env.DATA_TYPE_EMAIL,
		name: () => 'Email',
		label: () => 'Email',
		placeholder: () => 'user@email.com',
		defaultValue: () => '',
		component: () => React.lazy(() => import('components/Input/Email')),
	},
	[process.env.DATA_TYPE_URL]: {
		id: process.env.DATA_TYPE_URL,
		name: () => 'URL',
		label: () => 'URL',
		placeholder: () => '',
		defaultValue: () => '',
		component: () => React.lazy(() => import('components/Input/Url')),
	},
	[process.env.DATA_TYPE_PASSWORD]: {
		id: process.env.DATA_TYPE_PASSWORD,
		name: () => 'Пароль',
		label: () => 'Пароль',
		placeholder: () => 'Пароль',
		defaultValue: () => '',
		component: () => React.lazy(() => import('components/Input/Password')),
	},
	[process.env.DATA_TYPE_IMAGE]: {
		id: process.env.DATA_TYPE_IMAGE,
		name: () => 'Изображение',
		label: () => 'Изображение',
		placeholder: () => 'Изображение',
		defaultValue: () => '',
		component: () => React.lazy(() => import('components/Input/File')),
	},
	[process.env.DATA_TYPE_TIME]: {
		id: process.env.DATA_TYPE_TIME,
		name: () => 'Время',
		label: () => 'Время',
		placeholder: () => 'Время',
		defaultValue: () => '',
		component: () => React.lazy(() => import('components/Input/Time')),
	},
	[process.env.DATA_TYPE_DATE]: {
		id: process.env.DATA_TYPE_DATE,
		name: () => 'Дата',
		label: () => 'Дата',
		placeholder: () => 'Дата',
		defaultValue: () => '',
		component: () => React.lazy(() => import('components/Input/Date')),
	},
	[process.env.DATA_TYPE_DATETIME]: {
		id: process.env.DATA_TYPE_DATETIME,
		name: () => 'Дата и время',
		label: () => 'Дата и время',
		placeholder: () => 'Дата и время',
		defaultValue: () => '',
		component: () => React.lazy(() => import('components/Input/DateTime')),
	},
};

export default dataType;
